### Perceptron

In [18]:
# 导入相关库
import pandas as pd
import numpy as np
from sklearn.datasets import load_iris
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split

In [2]:
iris = load_iris()
df = pd.DataFrame(iris.data, columns=iris.feature_names)
df['label'] = iris.target
df.columns = ['sepal length', 'sepal width', 'petal length', 'petal width', 'label']
df.label.value_counts()

0    50
1    50
2    50
Name: label, dtype: int64

In [16]:
data = np.array(df.iloc[:100])
X, y = data[:,:-1], data[:,-1]
y = np.array([1 if i == 1 else -1 for i in y])
print(X.shape, y.shape)

(100, 4) (100,)


In [19]:
train_X, test_X, train_y, test_y = train_test_split(X, y, test_size=0.2)

In [41]:
class Perceptron:
    
    def __init__(self, dim, lr, max_epoch):
      self.dim = dim
      self.lr = lr
      self.max_epoch = max_epoch
      
      self.W, self.b = self.initialization()
    
    def initialization(self):
        W = np.zeros(self.dim, dtype=np.float64)
        b = 0.0
        return W, b
    
    def sign(self, x, y):
        
        return y * (np.dot(x, self.W) + self.b)
    
    def fit(self, X, y):
        
        has_wrong_pred = True
        
        while has_wrong_pred:
            wrong_pred_count = 0
            for ep, idx in enumerate(range(len(X))):
                if ep+1 >= self.max_epoch:
                    break
                xi, yi = X[idx], y[idx]
            
                if self.sign(xi, yi) <= 0:
                    
                    self.W = self.W + self.lr * np.dot(yi, xi)
                    self.b = self.b + self.lr * yi
                    wrong_pred_count += 1
            print(self.W,self.b)
                    
            if wrong_pred_count == 0:
                has_wrong_pred = False
                print("There is no missclassification")
                    
    def predict(self, X, y):
        
        num_total = len(X)
        num_correct = 0
        for idx in range(num_total):
            xi, yi = X[idx], y[idx]
            
            if self.sign(xi, yi) > 0:
                num_correct+=1
        return num_correct / num_total
    
    def params(self):
        
        return self.W, self.b
            
                    

In [43]:
model = Perceptron(train_X.shape[-1], 0.1, 4)
model.fit(train_X, train_y)
accuracy = model.predict(test_X, test_y)
accuracy

[ 0.04 -0.04  0.29  0.11] 0.0
[-0.46 -0.38  0.13  0.07] -0.1
[-0.42 -0.42  0.42  0.18] -0.1
[-0.38 -0.46  0.71  0.29] -0.1
[-0.33 -0.56  0.93  0.36] -0.1
[-0.33 -0.56  0.93  0.36] -0.1
There is no missclassification


1.0